
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from guiMain import *
from tkinter import *

# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Label,Image
import tkinter
import sqlite3
# Ne conectam la baza de date]
conn = sqlite3.connect('SmartRecipeDatabase1.db')
from guiLogin import LoginF
# Creem un cursor cursor 
cursor = conn.cursor()

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assetsRegister\frame0")
def ChangeState(text,var):
    var.set(text)
    return 1
def Login():
    print('it works')
    LoginF()

def Register():
    print('it works')
    RegisterF()
def addUser(entry_1, entry_2, entry_3, entry_4,var):
    if len(entry_4.get()) >= 3 and len(entry_4.get()) <=24:
        cursor.execute("SELECT * FROM UserView")
        rows = cursor.fetchall()
        users = []
        for row in rows:
            users.append(str(row[0]))
        if entry_4.get() not in users:
            if len(entry_1.get()) >= 3 and len(entry_1.get()) <=50 and '@' in entry_1.get():
                if len(entry_2.get()) >= 3 and len(entry_2.get()) <=25:
                    if entry_3.get() == entry_2.get():
                        cursor.execute(f"Insert into Auth (userName,userPassword,userEmail,roleId) values ('{entry_4.get()}','{entry_2.get()}','{entry_1.get()}',2)")
                        conn.commit()
                        ChangeState("You Added User, You may Login ",var)
                    else:
                        ChangeState('Password is not equal ',var)
                else:
                    ChangeState('Your passwoord is not allowed ',var)
            else:
                ChangeState('Incorrect email  ',var)
        else:
            ChangeState("You already Added this User",var)
    else:
        ChangeState('Incorrect Username',var)
    return 0

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def RegisterF():
    window = Tk()

    window.geometry("1366x768")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 768,
        width = 1366,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        50.0,
        43.0,
        1316.0,
        711.0,
        fill="#F2E3DB",
        outline="")

    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        436.0,
        377.0,
        image=image_image_1
    )

    canvas.create_text(
        908.0,
        290.0,
        anchor="nw",
        text="Username",
        fill="#E86A33",
        font=("Basic Regular", 12 * -1)
    )

    canvas.create_text(
        908.0,
        340.0,
        anchor="nw",
        text="Email",
        fill="#E86A33",
        font=("Basic Regular", 12 * -1)
    )
    canvas.create_text(
        909.0,
        395.0,
        anchor="nw",
        text="Password",
        fill="#E86A33",
        font=("Basic Regular", 12 * -1)
    )

    canvas.create_text(
        910.0,
        445.0,
        anchor="nw",
        text="Repeat password",
        fill="#E86A33",
        font=("Basic Regular", 12 * -1)
    )

    entry_1 = Entry(
        bd=0,
        bg="#bfdcc3",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=910.0,
        y=359.0,
        width=312.0,
        height=32.0
    )
    entry_2 = Entry(
        bd=0,
        bg="#bfdcc3",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=911.0,
        y=412.0,
        width=312.0,
        height=32.0
    )
    entry_3 = Entry(
        bd=0,
        bg="#bfdcc3",
        fg="#000716",
        highlightthickness=0
    )
    entry_3.place(
        x=912.0,
        y=464.0,
        width=312.0,
        height=32.0
    )

    entry_bg_4 = canvas.create_image(
        1064.0,
        324.0
    )
    entry_4 = Entry(
        bd=0,
        bg="#bfdcc3",
        fg="#000716",
        highlightthickness=0
    )
    entry_4.place(
        x=908.0,
        y=307.0,
        width=312.0,
        height=32.0
    )

    button_1 = Button(
        borderwidth=0,
        highlightthickness=0,
        command=lambda: addUser(entry_1, entry_2, entry_3, entry_4,var),
        relief="flat",
        bg="#507b57",
        text= "Ok"
    )
    button_1.place(
        x=1060.0,
        y=581.0,
        width=156.00634765625,
        height=39.0
    )

    canvas.create_text(
        904.0,
        220.0,
        anchor="nw",
        text="Welcome",
        fill="#000000",
        font=("Basic Regular", 36 * -1)
    )
    var = tkinter.StringVar()
    label_5 = Label(
        bd=0,
        bg="#f2e3db",
        fg="#000716",
        textvariable= var,
        highlightthickness=0
    )
    label_5.place(
        x=906.0,
        y=540.0,
        width=312.0,
        height=32.0
    )

    button_2 = Button(
        borderwidth=0,
        highlightthickness=0,
        bg="#507b57",
        text= "Register",
        command=lambda: Register(),
        relief="flat"
    )
    button_2.place(
        x=1060.0,
        y=142.0,
        width=157.0,
        height=40.0
    )

    canvas.create_text(
        1060.0,
        143.0,
        anchor="nw",
        text="Register",
        fill="#000000",
        font=("Basic Regular", 15 * -1)
    )
    button_3 = Button(
        borderwidth=0,
        highlightthickness=0,
        command=lambda: Login(),
        relief="flat",
        bg="#bfdcc3",
        text= "Login"
    )
    button_3.place(
        x=904.0,
        y=142.0,
        width=156.0,
        height=40.0
    )

    canvas.create_text(
        904.0,
        143.0,
        anchor="nw",
        text="Login",
        fill="#FFFFFF",
        font=("Basic Regular", 15 * -1)
    )

    canvas.create_text(
        904.0,
        92.0,
        anchor="nw",
        text="Smart Recipes",
        fill="#E86A33",
        font=("Basic Regular", 40 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
    return 1
